### ISSUE TITLE
conda package for 1.10?

### ISSUE THREAD

**Issue by bernt-matthias** [computational-metabolomics/mspurity-galaxy#14]
During installation I get:

```
PackageNotFoundError: Packages missing in current channels:
            
  - bioconductor-mspurity 1.10.0*
```

**Comment by Tomnl** [comment]
Hi @bernt-matthias 

I am currently waiting for the bioconda bioconductor-mspurity release of 1.11. 

In the mean time you need to add my personal conda channel "tomnl" to Galaxy, i.e.

* Update the galaxy.yml to `conda_ensure_channels: tomnl,iuc,conda-forge,bioconda,defaults`
* Or add `--conda_ensure_channels tomnl,iuc,bioconda,conda-forge,defaults` to the planemo call

**Comment by bernt-matthias** [comment]
Installation of the conda package worked, but it seems unusable: 


```
Fatal error: Exit code 1 ()
Loading required package: Rcpp
Error: package or namespace load failed for ?msPurity? in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/gpfs0/home/huberc/R/x86_64-pc-linux-gnu-library/3.4/stringi/libs/stringi.so':
  libicui18n.so.55: cannot open shared object file: No such file or directory
In addition: Warning message:
package ?Rcpp? was built under R version 3.4.3 
Execution halted
```

**Comment by bernt-matthias** [comment]
Hmm. That's at least what the galaxy error report of a user says ... If I try to reproduce it libraries load nicely. Have to check this.

**Comment by bernt-matthias** [comment]
Turns out that the error is due to the interference with a library (stringi) that the user installed in their home.

**Comment by Tomnl** [comment]
Hi @bernt-matthias 

OK, I was having a few issues with conda as well a few weeks back (but unrelated to this I think). 

If you still get problems, it might worth remove the current "__biconductor-mspurity" environment from conda completely and install again.

**Comment by Tomnl** [comment]
Now using bioconductor version 1.12.0
