### ISSUE TITLE
createMSP error

### ISSUE THREAD

**Issue by bernt-matthias** [computational-metabolomics/mspurity-galaxy#16]
We have the following error for createMSP: 

```
Error in msPurity::createMSP(pa, msp_file_pth = file.path(opt$out_dir,  : 
  object 'pa' not found
```

input comes from `xcms findChromPeaks (xcmsSet) Chromatographic peak detection (Galaxy Version 3.4.4.0)`

I guess its an incompatibility with this newer 

Was also wondering if the input data type of the tool should be: `rdata.xcms.findchrompeaks` (which seems to be xcms.set output type in 3.x) or `rdata.xcms.raw` (which seems to be xcms.set output type in 2.x)

**Comment by Tomnl** [comment]
hi @bernt-matthias ,

The createMSP tool should use the purityA object as input (after frag4feature and any other processing). 

e.g.

* Purity assessments
    * (mzML files) -> purityA -> (pa)
* XCMS processing (old functions used here but should work with xcms>=3
    * (mzML files) -> xcms.xcmsSet -> xcms.merge -> xcms.group -> xcms.retcor -> xcms.group
-> (xset)
* Fragmentation processing
    * (xset, pa) -> frag4feature -> filterFragSpectra -> averageFragSpectra  -> createMSP -> (MSP file)

The documentation in the Galaxy tool is a bit lacking but the R documentation is a bit more in depth. See https://bioconductor.org/packages/release/bioc/manuals/msPurity/man/msPurity.pdf

**Comment by bernt-matthias** [comment]
Hi @Tomnl. Thanks for the response. At the moment we only want to use msPurity functionality for creating msp files from mzML files. What would be the preferred workflow for this?

However, I would suggest to use more specific Galaxy data types than `rdata` to help users to select  inputs of the correct type.

**Comment by Tomnl** [comment]
What MS/MS do you want? i.e.

* Every single MS/MS scan in the mzML file?
* Every single MS/MS scan associated with an XCMS grouped feature?
* Averaged MS/MS per XCMS grouped feature?

I will make an issue for the data types. 

PS - I am making some updates at the moment that might fix some bugs. Are you using the testtoolshed or working directly from the github code?

**Comment by chufz** [comment]
Hi Tomni, 
for the moment we would prefer to  get Every single MS/MS scan associated with an XCMS grouped feature, extract the msp, show how strong they variate among the sample set and use them further for use in metfrag / cfm

**Comment by Tomnl** [comment]
Hi @chufz 

The minimum workflow with msPurity for that would be the following:

* Purity assessments
    * (mzML files) -> purityA -> (pa)
* XCMS processing (old functions used here but should work with xcms>=3
    * (mzML files) -> xcms.xcmsSet -> xcms.merge -> xcms.group -> (xset)
* Fragmentation processing
    * (xset, pa) -> frag4feature ->  createMSP  -> (MSP file with all the fragmentation)

For createMSP - make sure the option for "How to choose fragmentation spectra" is set to "all". This will create an MSP file with all the MS/MS associated with each XCMS feature.

However, from my experience it is better to at least average the spectra (and in some cases perform some basic filtering)

 (xset, pa) -> frag4feature -> filterFragSpectra -> averageFragSpectra  -> createMSP

**Comment by Tomnl** [comment]
Could I check as well, are you installing directly from the testoolshed or from the github repo?

**Comment by bernt-matthias** [comment]
I installed for testing directly from the repo, I'm at the latest commit 4059acdcf7d5a98124d796b83934e4ee2ad3859e

**Comment by Tomnl** [comment]
Thanks @bernt-matthias, I am planning to merge to some updates from #15  by the end of the day. I will let you know when they are merged with stable and passing.

**Comment by bernt-matthias** [comment]
Thanks

**Comment by Tomnl** [comment]
#15 has been merged now

**Comment by bernt-matthias** [comment]
updated. thanks
