### ISSUE TITLE
Can't obtain results from assess-purity for a file

### ISSUE THREAD

**Issue by jsaintvanne** [computational-metabolomics/mspurity-galaxy#2]
Hi,
I try to obtain some results with a file containing MS2 scans. I process xset with the file containing fullMS (file005) and msPurity with the other one wich contains only MS2 scans (file006). With msnbase tool I can confirm the  content of each file : 
```
> xset<-readMSData("./Documents/Mix22_STD_Laberca/20170901_005.mzML",mode="onDisk")
> xset
MSn experiment data ("OnDiskMSnExp")
Object size in memory: 0.7 Mb
- - - Spectra data - - -
 MS level(s): 1 
 Number of spectra: 2259 
 MSn retention times: 0:0 - 22:1 minutes
- - - Processing information - - -
Data loaded [Thu May  3 09:34:13 2018] 
 MSnbase version: 2.4.2 
- - - Meta data  - - -
phenoData
  rowNames: 20170901_005.mzML
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  20170901_005.mzML 
protocolData: none
featureData
  featureNames: F1.S0001 F1.S0002 ... F1.S2259 (2259 total)
  fvarLabels: fileIdx spIdx ... spectrum (28 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
> xset<-readMSData("./Documents/Mix22_STD_Laberca/20170901_006.mzML", mode="onDisk")
> xset
MSn experiment data ("OnDiskMSnExp")
Object size in memory: 2.89 Mb
- - - Spectra data - - -
 MS level(s): 2 
 Number of spectra: 9634 
 MSn retention times: 0:1 - 22:0 minutes
- - - Processing information - - -
Data loaded [Thu May  3 09:40:19 2018] 
 MSnbase version: 2.4.2 
- - - Meta data  - - -
phenoData
  rowNames: 20170901_006.mzML
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  20170901_006.mzML 
protocolData: none
featureData
  featureNames: F1.S0001 F1.S0002 ... F1.S9634 (9634 total)
  fvarLabels: fileIdx spIdx ... spectrum (28 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
```

All is good to process xcms with the first file. The problem is when I would like to process purityA function on the second file. The tool tell me that it can't find any MS/MS spectra... And when I perform it on my local Galaxy with the tool "assess-purity", I obtain a file with only "". Here is the error when I run it w```ith commandline : 
```
> pa<-purityA("./Documents/Mix22_STD_Laberca/20170901_006.mzML")
No MS/MS spectra for file:  ./Documents/Mix22_STD_Laberca/20170901_006.mzML
```

Please can someone help me?

I can send you the files if you want ? (can't attach it here the format is not good)

Thanks

Cheers,
Julien

**Comment by Tomnl** [comment]
Hi Julien,

Could you send me the file via email and I will look into this.

Also, please let me know how you converted the file from RAW format to mzML format (e.g proteowizard settings and version used) 

Cheers,
Tom

**Comment by Tomnl** [comment]
copied from email

> 
> That file does not have MS1 data. So msPurity won't be able to work with it, the file needs to have both MS1 and MS2 scans in the same file to work with the assess_purity (purityA) functionality.
> 
> No quick solution for this at the moment. Sorry...

Will close for now but the option to use assess_purity (purityA) where the MS1 and MS2 are in different files would be useful.
