### ISSUE TITLE
createMSP generates duplicate entries in msp files

### ISSUE THREAD

**Issue by bernt-matthias** [computational-metabolomics/mspurity-galaxy#21]
In the msp files every entry seems to be duplicated:

```
RECORD_TITLE:  MZ:72.0808 | RT:101.1 | grpid:3 | file:2
MS$FOCUSED_ION: PRECURSOR_M/Z 72.0807647705078
AC$CHROMATOGRAPHY: RETENTION_TIME 101.089805159508
XCMS groupid (grpid): 3
COMMENT: Exported from msPurity purityA object using function createMSP, using method 'max' msPurity version:1.11.0 
PK$NUM_PEAK: 13
PK$PEAK: m/z int. rel.int.
55.0182762145996	9395.638671875	0.8
55.0546035766602	49546.16015625	4.22
56.0497970581055	7668.17724609375	0.65
57.0576171875	19782.62890625	1.68
58.3162040710449	3561.248046875	0.3
59.9023933410645	3287.33129882812	0.28
69.1670455932617	3629.53637695312	0.31
69.1704025268555	6699.1572265625	0.57
69.3209609985352	3323.13623046875	0.28
70.065185546875	3312.5732421875	0.28
72.0444946289062	152805.625	13
72.0485534667969	7866.34326171875	0.67
72.0808715820312	1175112.875	100

RECORD_TITLE:  MZ:72.0808 | RT:101.1 | grpid:3 | file:2
MS$FOCUSED_ION: PRECURSOR_M/Z 72.0807647705078
AC$CHROMATOGRAPHY: RETENTION_TIME 101.089805159508
XCMS groupid (grpid): 3
COMMENT: Exported from msPurity purityA object using function createMSP, using method 'max' msPurity version:1.11.0 
PK$NUM_PEAK: 13
PK$PEAK: m/z int. rel.int.
55.0182762145996	9395.638671875	0.8
55.0546035766602	49546.16015625	4.22
56.0497970581055	7668.17724609375	0.65
57.0576171875	19782.62890625	1.68
58.3162040710449	3561.248046875	0.3
59.9023933410645	3287.33129882812	0.28
69.1670455932617	3629.53637695312	0.31
69.1704025268555	6699.1572265625	0.57
69.3209609985352	3323.13623046875	0.28
70.065185546875	3312.5732421875	0.28
72.0444946289062	152805.625	13
72.0485534667969	7866.34326171875	0.67
72.0808715820312	1175112.875	100
```

For your reference this is the workflow we are using:

[Galaxy-Workflow-Workflow_xcms_MSpurity_msp.zip](https://github.com/computational-metabolomics/mspurity-galaxy/files/3320572/Galaxy-Workflow-Workflow_xcms_MSpurity_msp.zip)

ping @chufz

**Comment by Tomnl** [comment]
Hi @bernt-matthias,

Sorry I thought I fixed this. When did you install msPurity with conda for this run?

**Comment by bernt-matthias** [comment]
Just today using following command: `/conda create -y --quiet --override-channels --channel tomnl --channel iuc --channel bioconda --channel conda-forge --channel defaults --name __bioconductor-mspurity@1.11.1 bioconductor-mspurity=1.11.1`

**Comment by Tomnl** [comment]
Can't seem to replicate this. Could you send me RData file please?

**Comment by bernt-matthias** [comment]
@chufz can you provide the file here?

**Comment by chufz** [comment]
i will opload it to a cloud and send you the link @Tomnl

**Comment by Tomnl** [comment]
thanks @chufz 

I have updated the bioconductor-mspurity (now on v1.11.2) on my conda channel and updated the tools here #23 and on the toolshed  . I think that will fix it for you

I think it might be to do with an old biconductor-mspurity of 1.11.1 build being used because I couldn't replicate the issue on my local machine

**Comment by bernt-matthias** [comment]
hi @chufz . I updated our local installation of mspurity. could you test?

@Tomnl : another remark: Since its less confusing for the users I always like if the tool version is identical to the version of the actual software. If there are multiple versions of the wrapper for the same software version one might append for instance `+galaxyX` (which is the IUC recommendation - see https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html).

**Comment by Tomnl** [comment]
thanks both

@bernt-matthias - that does look like a sensible approach to handling versioning! I will update then based on the IUC recommendation

**Comment by chufz** [comment]
I tested it and the msp file looks now fine, thanks :)
The issue can be closed.

**Comment by Tomnl** [comment]
Good to hear. Thanks @bernt-matthias @chufz
