### ISSUE TITLE
mspurity remarks

### ISSUE THREAD

**Issue by bernt-matthias** [computational-metabolomics/mspurity-galaxy#22]
I would remove the input from filesystem: 

https://github.com/computational-metabolomics/mspurity-galaxy/blob/f4b9813e5ac0ac76ce8dda955408a72a5d6c7de6/tools/msPurity/purityA.xml#L68

You may also consider to make this https://github.com/computational-metabolomics/mspurity-galaxy/blob/f4b9813e5ac0ac76ce8dda955408a72a5d6c7de6/tools/msPurity/purityA.xml#L64

a `type="data"` input field with `multiple="true"`. Then users can upload collections and selections of 1 or more data sets.

**Comment by Tomnl** [comment]
Good points

The library option is available for historic workflows but I could remove for future versions of the tool.

I will look into changing the input type as well

**Comment by bernt-matthias** [comment]
Another one: does createDatabase really need the `libgfortran` requirement?

**Comment by Tomnl** [comment]
This was a temp fix so that I could get CAMERA to install (I think..) as I was getting some errors. (createDatabase - can use the CAMERA object instead of an XCMS object if required).

I will check to see if it is still a problem and the extra requirement can be removed

**Comment by Tomnl** [comment]
Both issues now addressed
