### ISSUE TITLE
spectralMatching question

### ISSUE THREAD

**Issue by jsaintvanne** [computational-metabolomics/mspurity-galaxy#35]
Hi Thomas,

During the spectral matching, we can choose if we add the output of `createDatabase` function or your pre-created database or also a localy database. But when we choose the locally database, we can't add any file... See here : 
https://github.com/computational-metabolomics/mspurity-galaxy/blob/master/tools/msPurity/macros.xml#L122

Is it normal and I missed something ? Or it really miss something to enter our file ?

Thanks 

Julien

**Comment by Tomnl** [comment]
Hi Julien,

You can use a locally configured database defined here

https://github.com/computational-metabolomics/mspurity-galaxy/blob/master/tools/msPurity/dbconfig.R

This needs to be updated in the tool folder after installation on a Galaxy instance

**Comment by jsaintvanne** [comment]
Ok thanks for the link I will add it on my GTN to have an example of how you can build your database!

Ho I see! so I can write in GTN that we have to add the file and it will be correct soon in the Galaxy part ?

Thanks for the answer !
