### ISSUE TITLE
Error Galaxy msPurity.spectralMatching with mona_nov_parsed_20181120122122.db

### ISSUE THREAD

**Issue by yguitton** [computational-metabolomics/mspurity-galaxy#39]
Hi Tom, Hi Ralf,
I hope that your both fine,

I'm using msPurity under workflow4metabolomics.usegalaxy.fr and everything was fine, with all default parameters, until I tried to upload the complete mona_nov_parsed_20181120122122.db

I have  the following error

Loading required package: Rcpp
Running msPurity spectral matching function for LC-MS(/MS) data
Error in if (is.na(l_dbPth)) { : argument is of length zero
Calls: <Anonymous>
Execution halted

It seems that the db is not found, If you have some time to investigate, my history is here
https://workflow4metabolomics.usegalaxy.fr/u/yguitton44/h/qva-iterative-dda

Many thanks
Yann

**Comment by Tomnl** [comment]
Hi Yann,

Sorry about this.. seems like a bug in the Galaxy wrapper when choosing the SQLite input. I will look into it now

In the meantime - If you have access to update the toolshed file on the Galaxy server - it should work by updating the local config (defined [ here](https://github.com/computational-metabolomics/mspurity-galaxy/blob/master/tools/msPurity/dbconfig.R)) just set `l_dbPth <- "/path/2/sqlite/library.db"`  and `l_dbType <- "sqlite"`

**Comment by yguitton** [comment]
Hi Tom,
Thanks for the quick reply.

If it's a wrapper issue, I can wait until the upload of a new version on the toolshed. Just let us know when this small beug is corrected and I can ask @lecorguille to update the wrapper.

 In the mean time I will try to work within Rstudio on my own PC
Best
Yann

**Comment by Tomnl** [comment]
OK. Thanks for letting me know. I've hopefully fixed it now.

I just need to make sure all the tests pass, merge and push it to the toolshed

**Comment by Tomnl** [comment]
Hi @yguitton - the fix should now be in the most recent version on the toolshed so I am going to close now. Let me know if you still have any other issues
