### ISSUE TITLE
peaklist of MSMS centroided

### ISSUE THREAD

**Issue by jsaintvanne** [computational-metabolomics/mspurity-galaxy#4]
Hi Thomas !

Do you think that's possible to centroid the MSMS spectra ?

Say that cause after the MSP file generation, I obtain the peaklist for my interest MS peak, but the MSMS spectra are ot centroided like the example here
![image](https://user-images.githubusercontent.com/35449860/41289089-d8148998-6e48-11e8-84c3-1ce7deb545b2.png)

So is there already something to do it? Or do you think something is possible to do this?

Thanks !
Julien

**Comment by Tomnl** [comment]
Yep, looks like it is profile, how did you run msconvert?

```
msconvert *.raw --mzML --64 --zlib -o mzml --filter "peakPicking true 1-"  positive "positive"
```

Need to make sure the peakPicking option is set to `peakPicking true 1-`

**Comment by jsaintvanne** [comment]
Ok thanks ! I will ask it to @yguitton who transformed the raw files !

**Comment by yguitton** [comment]
Hi @Tomnl and @jsaintvanne 
I have used the graphical version of MSconvert with peakpicking vendor set to True
I will re-run the conversion with commandline

yann

**Comment by Tomnl** [comment]
@jsaintvanne  @yguitton 

I can also have a look at the file if you want to send me a link to it (both raw and mzML)

**Comment by jsaintvanne** [comment]
Thanks @yguitton  !! Tell me if it is good for you ?

@Tomnl  here is the link to the raw file https://filesender.renater.fr/?s=download&token=0919dfb0-3438-958f-d505-31f67b51428d
I work on it with only positive ionisations cause xcms lookshave trouble when the switching datas...

**Comment by yguitton** [comment]
Hi @Tomnl and @jsaintvanne 
In fact I have used peakpicking true 1 and note 1- 
the new files are here https://filesender.renater.fr/?s=download&token=0d24d3ea-fb4b-1452-1491-0f178d045a9f
and the MSMS are now centroided

yann

**Comment by jsaintvanne** [comment]
OK that's looks good for me !! 
I run : 
```R
msconvert file.raw --mzML --64 -o outpuDir --filter "peakPicking true 1-" --filter "polarity positive"
```
on my Windows and then process my file !
I can find the same peak matching after frag4feature and then the MS2 scans are centroided !! :)

Thanks for your help Thomas !

**Comment by Tomnl** [comment]
Great! I will close this issue now then
