### ISSUE TITLE
Dataset Error Report

### ISSUE THREAD

**Issue by Vignesh291** [computational-metabolomics/mspurity-galaxy#51]
Hi
I received the error while trying to create a database (mspurity)

An error occurred while running the tool toolshed.g2.bx.psu.edu/repos/computational- metabolomics/mspurity_createdatabase/mspurity_createdatabase/1.16.2+galaxy1.

Details
Execution resulted in the following messages:

Fatal error: Exit code 1 ()

Tool generated the following standard error:

Loading required package: Rcpp
Warning messages:
1: package ‘msPurity’ was built under R version 4.0.3
2: package ‘Rcpp’ was built under R version 4.0.3
Loading required package: Biobase
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
clusterExport, clusterMap, parApply, parCapply, parLapply,
parLapplyLB, parRapply, parSapply, parSapplyLB
The following objects are masked from ‘package:stats’:

IQR, mad, sd, var, xtabs
The following objects are masked from ‘package:base’:

anyDuplicated, append, as.data.frame, basename, cbind, colnames,
dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
union, unique, unsplit, which.max, which.min
Welcome to Bioconductor

Vignettes contain introductory material; view with
'browseVignettes()'. To cite Bioconductor, see
'citation("Biobase")', and for packages 'citation("pkgname")'.
Loading required package: BiocParallel
Loading required package: MSnbase
Loading required package: mzR
Loading required package: S4Vectors
Loading required package: stats4

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

expand.grid
Loading required package: ProtGenerics

Attaching package: ‘ProtGenerics’

The following object is masked from ‘package:stats’:

smooth
This is MSnbase version 2.16.0
Visit https://lgatto.github.io/MSnbase/ to get started.

Attaching package: ‘MSnbase’

The following object is masked from ‘package:base’:

trimws
This is xcms version 3.12.0

Attaching package: ‘xcms’

The following object is masked from ‘package:stats’:

sigma
Warning messages:
1: package ‘xcms’ was built under R version 4.0.3
2: package ‘Biobase’ was built under R version 4.0.3
3: package ‘BiocParallel’ was built under R version 4.0.3
4: package ‘MSnbase’ was built under R version 4.0.3
5: package ‘mzR’ was built under R version 4.0.3
6: package ‘S4Vectors’ was built under R version 4.0.3
7: package ‘ProtGenerics’ was built under R version 4.0.3
Warning message:
package ‘CAMERA’ was built under R version 4.0.3
Note: you might want to set/adjust the 'sampclass' of the returned xcmSet object before proceeding with the analysis.
Creating a database of fragmentation spectra and LC features
Error in $<-.data.frame(*tmp*, "grp_name", value = c("M451T96", "M451T1042", :
replacement has 426 rows, data has 696
Calls: -> export2sqlite -> 
&lt;-.data.frame
Execution halted

**Comment by Tomnl** [comment]
Hi @Vignesh291,

Might be to do with the XCMS dataset that was used.

Could I check what parameters and input you used? (or if using a public instance could you share your history)

**Comment by Tomnl** [comment]
I am going to close this - but please comment to reopen if you would like me to investigate more
