### ISSUE TITLE
[purityA] File naming error in output files

### ISSUE THREAD

**Issue by Hrodwin** [computational-metabolomics/mspurity-galaxy#56]
Hi,
When using purityA with my datasets, I encountered a file naming problem that is as such; in the output .tsv summarizing the features and their purity specifications, the files are named starting from the first file of the collection, and not from the first file containing MS/MS data. Then the recorded data do not correspond to the file cited in the "filename" column of the .tsv. Here is an illustration of this behaviour:

![image](https://github.com/user-attachments/assets/d3c7ec89-d731-486d-855f-2e2a63837940)

I checked manually, and results given as belonging to the file "_Blank5_POS_RA1_1_6735_" indeed belong to "_Pool_TestConst_DDA12-40step_POS_BD1_1_7615_", "_Blank6_POS_RA1_1_6736_" to "_Pool_TestConst_DDA12ev_POS_BD1_1_7611_" and so on...

Best,
Quentin

**Comment by Tomnl** [comment]
Hi @Hrodwin - please could you provide a Galaxy history of this?

I will look into it

**Comment by Tomnl** [comment]
Ah I think i see where the error is

**Comment by Tomnl** [comment]
OK - was an error in the Galaxy wrapper script - needed to convert from factor to string. Just testing now

**Comment by Tomnl** [comment]
@Hrodwin - this should be fixed in v1.28.0+galaxy1 🤞

**Comment by Hrodwin** [comment]
Problem solved with the update! Thank you 👍

**Comment by Tomnl** [comment]
Great! Thanks for letting me know. I will close the issue now.
